-- Supabase Migration Script from SQLite
-- Generated by Gemini

-- 1. Create the custom schema for system-wide, read-only data.
CREATE SCHEMA IF NOT EXISTS system_content;

-- =================================================================
-- Schema: system_content
-- Contains tables with system-provided data.
-- =================================================================

-- Table: system_content.body_part
CREATE TABLE system_content.body_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(50)
);

-- Table: system_content.target_muscle
CREATE TABLE system_content.target_muscle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(50)
);

-- Table: system_content.equipment
CREATE TABLE system_content.equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(50)
);

-- Table: system_content.action
CREATE TABLE system_content.action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(50) UNIQUE,
    name VARCHAR(100) NOT NULL,
    "gifUrl" VARCHAR(200),
    description TEXT,
    difficulty VARCHAR(20),
    bodypart_id BIGINT NOT NULL REFERENCES system_content.body_part(id),
    equipment_id BIGINT REFERENCES system_content.equipment(id),
    is_bilateral BOOLEAN DEFAULT false,
    name_en VARCHAR(255),
    description_en TEXT
);

-- Table: system_content.article
CREATE TABLE system_content.article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    image_filename VARCHAR(100),
    pub_date TIMESTAMP WITH TIME ZONE NOT NULL,
    title_en VARCHAR(200),
    content_en TEXT
);

-- Table: system_content.site_config
CREATE TABLE system_content.site_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" VARCHAR(50) NOT NULL UNIQUE,
    value TEXT
);

-- Table: system_content.database_version
CREATE TABLE system_content.database_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL,
    build_number INTEGER NOT NULL,
    update_date TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Link Tables in system_content

CREATE TABLE system_content.bodypart_target_muscle_link (
    bodypart_id BIGINT NOT NULL REFERENCES system_content.body_part(id),
    target_muscle_id BIGINT NOT NULL REFERENCES system_content.target_muscle(id),
    PRIMARY KEY (bodypart_id, target_muscle_id)
);

CREATE TABLE system_content.action_target_muscle_link (
    action_id BIGINT NOT NULL REFERENCES system_content.action(id),
    target_muscle_id BIGINT NOT NULL REFERENCES system_content.target_muscle(id),
    PRIMARY KEY (action_id, target_muscle_id)
);

CREATE TABLE system_content.video (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(200) NOT NULL,
    action_id BIGINT NOT NULL REFERENCES system_content.action(id)
);

-- New Table: system_content.training_plan_templates
-- For system-provided training plan templates.
CREATE TABLE system_content.training_plan_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    difficulty VARCHAR(20),
    duration INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc'''),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);


-- =================================================================
-- Schema: public
-- Contains tables with user-generated data.
-- =================================================================

-- Note: The 'user' table is replaced by Supabase's 'auth.users' table.
-- All 'user_id' columns will be UUID and reference auth.users(id).

-- Table: public.training_plans
CREATE TABLE public.training_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    difficulty VARCHAR(20),
    duration INTEGER,
    is_template BOOLEAN DEFAULT false, -- User's own template
    template_id BIGINT, -- Can reference system_content.training_plan_templates(id)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc'''),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);
-- Add foreign key to system templates separately
ALTER TABLE public.training_plans ADD FOREIGN KEY (template_id) REFERENCES system_content.training_plan_templates(id) ON DELETE SET NULL;


-- Table: public.plan_actions
CREATE TABLE public.plan_actions (
    plan_id BIGINT NOT NULL REFERENCES public.training_plans(id) ON DELETE CASCADE,
    action_id BIGINT NOT NULL, -- Can be from system_content.action or public.custom_actions
    "order" INTEGER,
    sets INTEGER,
    reps VARCHAR(50),
    rest INTEGER,
    weight REAL DEFAULT 10,
    note TEXT,
    record_bilateral BOOLEAN DEFAULT false,
    PRIMARY KEY (plan_id, action_id)
);
-- Note: We can't add a direct FK to both action tables. This will be handled at the application level.


-- Table: public.plan_sets
CREATE TABLE public.plan_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES public.training_plans(id) ON DELETE CASCADE,
    action_id BIGINT NOT NULL, -- Can be from system_content.action or public.custom_actions
    set_number INTEGER NOT NULL,
    weight REAL DEFAULT 10.0,
    reps INTEGER DEFAULT 12,
    left_weight REAL,
    right_weight REAL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.training_plan_executions
CREATE TABLE public.training_plan_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES public.training_plans(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.execution_actions
CREATE TABLE public.execution_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL REFERENCES public.training_plan_executions(id) ON DELETE CASCADE,
    action_id BIGINT NOT NULL, -- From system_content.action or public.custom_actions
    action_name TEXT NOT NULL,
    order_num INTEGER NOT NULL,
    rest INTEGER,
    is_bilateral BOOLEAN NOT NULL DEFAULT false,
    record_bilateral BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.execution_sets
CREATE TABLE public.execution_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_action_id BIGINT NOT NULL REFERENCES public.execution_actions(id) ON DELETE CASCADE,
    set_number INTEGER NOT NULL,
    planned_weight REAL,
    planned_left_weight REAL,
    planned_right_weight REAL,
    planned_reps INTEGER NOT NULL,
    actual_weight REAL,
    actual_left_weight REAL,
    actual_right_weight REAL,
    actual_reps INTEGER,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    difficulty INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.training_sessions
CREATE TABLE public.training_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    plan_id BIGINT REFERENCES public.training_plans(id) ON DELETE SET NULL,
    execution_id BIGINT REFERENCES public.training_plan_executions(id) ON DELETE SET NULL,
    plan_name TEXT,
    status TEXT DEFAULT 'in_progress',
    total_volume REAL DEFAULT 0.0,
    completed_volume REAL DEFAULT 0.0,
    duration_minutes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- Table: public.training_history
CREATE TABLE public.training_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES public.training_sessions(id) ON DELETE CASCADE,
    plan_id BIGINT, -- Can be null
    plan_name TEXT,
    plan_description TEXT,
    training_date DATE NOT NULL,
    volume REAL DEFAULT 0.0,
    duration INTEGER DEFAULT 0,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.training_history_details
CREATE TABLE public.training_history_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id BIGINT NOT NULL REFERENCES public.training_history(id) ON DELETE CASCADE,
    action_id BIGINT NOT NULL, -- From system_content.action or public.custom_actions
    set_number INTEGER NOT NULL,
    weight REAL,
    weight_unit VARCHAR(3),
    reps INTEGER,
    difficulty VARCHAR(10),
    left_weight REAL,
    right_weight REAL,
    is_completed BOOLEAN DEFAULT false,
    note TEXT,
    history_record_bilateral BOOLEAN NOT NULL DEFAULT false
);

-- Table: public.body_measurements
CREATE TABLE public.body_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    measurement_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    weight_kg REAL NOT NULL,
    height_cm REAL NOT NULL,
    body_fat_percentage REAL NOT NULL,
    skeletal_muscle_mass_kg REAL NOT NULL,
    visceral_fat_level INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc'''),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- Table: public.password_reset_codes
CREATE TABLE public.password_reset_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    verification_code TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    is_used BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT (now() at time zone '''utc'''),
    used_at TIMESTAMPTZ
);

-- New Table: public.custom_actions
-- For user-defined actions.
CREATE TABLE public.custom_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    "gifUrl" VARCHAR(200),
    description TEXT,
    difficulty VARCHAR(20),
    bodypart_id BIGINT NOT NULL REFERENCES system_content.body_part(id),
    equipment_id BIGINT REFERENCES system_content.equipment(id),
    is_bilateral BOOLEAN DEFAULT false,
    name_en VARCHAR(255),
    description_en TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() at time zone '''utc''')
);

-- =================================================================
-- Enable Row Level Security (RLS) for user data
-- =================================================================

ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_plan_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execution_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execution_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_history_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.body_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_actions ENABLE ROW LEVEL SECURITY;

-- =================================================================
-- RLS Policies
-- =================================================================

-- Policy for training_plans: Users can manage their own plans.
CREATE POLICY "Allow individual access to own training plans"
ON public.training_plans
FOR ALL
USING (auth.uid() = user_id);

-- Policy for training_sessions: Users can manage their own sessions.
CREATE POLICY "Allow individual access to own training sessions"
ON public.training_sessions
FOR ALL
USING (auth.uid() = user_id);

-- Policy for training_history: Users can manage their own history.
CREATE POLICY "Allow individual access to own training history"
ON public.training_history
FOR ALL
USING (auth.uid() = user_id);

-- Policy for body_measurements: Users can manage their own measurements.
CREATE POLICY "Allow individual access to own body measurements"
ON public.body_measurements
FOR ALL
USING (auth.uid() = user_id);

-- Policy for custom_actions: Users can manage their own custom actions.
CREATE POLICY "Allow individual access to own custom actions"
ON public.custom_actions
FOR ALL
USING (auth.uid() = user_id);

-- For tables that don't have a direct user_id, access should be managed through joins in your application logic or using security barrier views.
-- For example, to access plan_actions, you must first have access to the training_plan.

-- Grant usage on schemas
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT USAGE ON SCHEMA system_content TO postgres, anon, authenticated, service_role;

-- Grant permissions for public schema
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- Grant permissions for system_content schema (read-only for users)
GRANT SELECT ON ALL TABLES IN SCHEMA system_content TO anon, authenticated;